### ISSUE TITLE
Try/catch observers in rrweb

### ISSUE THREAD

**Issue by Lms24** [getsentry/rrweb#25]
Our SDKs (+the integrations) should fail silently. So let's try/catch more parts of rrweb whcih are likely to fail:

https://github.com/getsentry/rrweb/issues/25#tasklist-block-3264abc6-028c-49b3-b808-c7866fe05fdc

Add other places here if identified

**Comment by billyvg** [comment]
@mydea can this be closed out now?

**Comment by mydea** [comment]
I think so, yes! we can always open new issues when needed.
