### ISSUE TITLE
TypeError Cannot read properties of undefined in Sentry Replay code

### ISSUE THREAD

**Issue by jessetan** [getsentry/rrweb#28]
### Environment

SaaS (https://sentry.io/)

### Version

sentry/nextjs 7.31.1

### Steps to Reproduce

We've got an issue in Sentry which seems to point at an error within Replay code.
The reported error is `TypeError Cannot read properties of undefined (reading 'prototype')` inside `styleSheetObserver`.
See screenshot below.
We have Replay sampling only turned on for errors, ironically it was able to capture a replay of the error it caused itself.

I can share the issue or replay privately if needed.

### Expected Result

I expect Replay to record interactions for errors, not cause errors itself.

### Actual Result

![Screenshot 2023-01-20 at 17 14 04](https://user-images.githubusercontent.com/3284111/213748621-0aec5e62-3893-4ccd-a402-77832ff82bd2.png)

**Comment by Lms24** [comment]
Hi @jessetan we just merged https://github.com/getsentry/sentry-javascript/pull/6856 which should fix this error. It'll be released in the next days.

We're tracking further rrweb-internal error handling in #25. Hence, I'm going to close this issue. Feel free to reply if you have additional questions or the fix doesn't work for you. Thanks!
