### ISSUE TITLE
Styles not rendered properly when seeking backwards in playback

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/rrweb#57]
### Environment

SaaS (https://sentry.io/)

### Version

- 

### Link

https://sentry.zendesk.com/agent/tickets/79673

### Steps to Reproduce

1. Navigate to linked Replay in Zendesk ticket
2. Skip ahead and then back using the player's slider
3. Observe that styles are not being rendered properly.

### Expected Result

Styles will be rendered properly when not requiring to be fetched in a way that violates CORS

### Actual Result

Styles are present but not rendered

**Comment by billyvg** [comment]
This issue is fixed in rrweb 2.0, please track https://github.com/getsentry/rrweb/issues/76 for updates
